# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import volume_pb2 as volume__pb2


class VolumeNodeStub(object):
  """////////////////////////////////////////////////

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AllocateVolume = channel.unary_unary(
        '/volume_pb.VolumeNode/AllocateVolume',
        request_serializer=volume__pb2.AllocateVolumeRequest.SerializeToString,
        response_deserializer=volume__pb2.AllocateVolumeResponse.FromString,
        )
    self.GetUsedSpace = channel.unary_unary(
        '/volume_pb.VolumeNode/GetUsedSpace',
        request_serializer=volume__pb2.GetUsedSpaceRequest.SerializeToString,
        response_deserializer=volume__pb2.GetUsedSpaceResponse.FromString,
        )
    self.WriteFile = channel.stream_unary(
        '/volume_pb.VolumeNode/WriteFile',
        request_serializer=volume__pb2.WriteFileChunk.SerializeToString,
        response_deserializer=volume__pb2.WriteFileResponse.FromString,
        )


class VolumeNodeServicer(object):
  """////////////////////////////////////////////////

  """

  def AllocateVolume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsedSpace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VolumeNodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AllocateVolume': grpc.unary_unary_rpc_method_handler(
          servicer.AllocateVolume,
          request_deserializer=volume__pb2.AllocateVolumeRequest.FromString,
          response_serializer=volume__pb2.AllocateVolumeResponse.SerializeToString,
      ),
      'GetUsedSpace': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsedSpace,
          request_deserializer=volume__pb2.GetUsedSpaceRequest.FromString,
          response_serializer=volume__pb2.GetUsedSpaceResponse.SerializeToString,
      ),
      'WriteFile': grpc.stream_unary_rpc_method_handler(
          servicer.WriteFile,
          request_deserializer=volume__pb2.WriteFileChunk.FromString,
          response_serializer=volume__pb2.WriteFileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'volume_pb.VolumeNode', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
