# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import master_pb2 as master__pb2


class MasterNodeStub(object):
  """////////////////////////////////////////////

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendHeartbeat = channel.stream_stream(
        '/master_pb.MasterNode/SendHeartbeat',
        request_serializer=master__pb2.Heartbeat.SerializeToString,
        response_deserializer=master__pb2.HeartbeatResponse.FromString,
        )
    self.KeepConnected = channel.stream_stream(
        '/master_pb.MasterNode/KeepConnected',
        request_serializer=master__pb2.KeepConnectedRequest.SerializeToString,
        response_deserializer=master__pb2.VolumeLocation.FromString,
        )
    self.LookupVolume = channel.unary_unary(
        '/master_pb.MasterNode/LookupVolume',
        request_serializer=master__pb2.LookupVolumeRequest.SerializeToString,
        response_deserializer=master__pb2.LookupVolumeResponse.FromString,
        )
    self.Assign = channel.unary_unary(
        '/master_pb.MasterNode/Assign',
        request_serializer=master__pb2.AssignRequest.SerializeToString,
        response_deserializer=master__pb2.AssignResponse.FromString,
        )
    self.VolumeList = channel.unary_unary(
        '/master_pb.MasterNode/VolumeList',
        request_serializer=master__pb2.VolumeListRequest.SerializeToString,
        response_deserializer=master__pb2.VolumeListResponse.FromString,
        )


class MasterNodeServicer(object):
  """////////////////////////////////////////////

  """

  def SendHeartbeat(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def KeepConnected(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LookupVolume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Assign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasterNodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendHeartbeat': grpc.stream_stream_rpc_method_handler(
          servicer.SendHeartbeat,
          request_deserializer=master__pb2.Heartbeat.FromString,
          response_serializer=master__pb2.HeartbeatResponse.SerializeToString,
      ),
      'KeepConnected': grpc.stream_stream_rpc_method_handler(
          servicer.KeepConnected,
          request_deserializer=master__pb2.KeepConnectedRequest.FromString,
          response_serializer=master__pb2.VolumeLocation.SerializeToString,
      ),
      'LookupVolume': grpc.unary_unary_rpc_method_handler(
          servicer.LookupVolume,
          request_deserializer=master__pb2.LookupVolumeRequest.FromString,
          response_serializer=master__pb2.LookupVolumeResponse.SerializeToString,
      ),
      'Assign': grpc.unary_unary_rpc_method_handler(
          servicer.Assign,
          request_deserializer=master__pb2.AssignRequest.FromString,
          response_serializer=master__pb2.AssignResponse.SerializeToString,
      ),
      'VolumeList': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeList,
          request_deserializer=master__pb2.VolumeListRequest.FromString,
          response_serializer=master__pb2.VolumeListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'master_pb.MasterNode', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
